#ifndef THEORYSPACE_GLOBAL_H
#define THEORYSPACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THEORYSPACE_LIBRARY)
#  define THEORYSPACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define THEORYSPACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THEORYSPACE_GLOBAL_H
